### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object. during long buring testing

### ISSUE THREAD

**Issue by Dennis3321** [hhblaze/Raft.Net#6]
I'm busy doing a burn-in test, fixed the previous memory leak, and now run into occasional errors;

    `[ERROR] [System.ObjectDisposedException: Cannot access a disposed object.
       at System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)
       at System.Threading.Timer.Change(Int32 dueTime, Int32 period)
       at System.Timers.Timer.UpdateTimer()
       at System.Timers.Timer.set_Interval(Double value)
       at Raft.TimeMaster.RecalculateTimer()] [Raft.TimeMaster.RecalculateTimer] []`

This occours only once every day on one of the nodes in a 5 node setup. I'm running two days now, and I see it only 3 times now.

**Comment by hhblaze** [comment]
It's okay, should not influent on the flight speed.
